### PR TITLE
Entrypoint change to dockerfile

### PR DESCRIPTION
**Pull request by alekssaul**
updateservicectl seem to get build in `/go/bin/updateservicectl`

### CODE REVIEW

**Comment by sym3tri** [comment]
LGTM. thanks.

**Comment by sym3tri** [comment]
This probably stopped working b/c we're doing `FROM google/golang`. This should really target a specific tag. Also `google/golang` is deprecated in favor of `golang`, so we should switch to that. @alekssaul are you up for making that change instead?

https://hub.docker.com/_/golang/

**Comment by alekssaul** [comment]
Changed base image to golang:1.6, dockerbuild and basic smoke tested.

**Comment by sym3tri** [comment]
thanks!

**Pull request merged**
