### PR TITLE
hawk-go: Update to master plus tent/hawk-go#7

### PR DESCRIPTION
**Pull request by silas**
This normalizes how URL.RequestURI is used within the Hawk normalized
request string.

### CODE REVIEW

**Comment by crawford** [comment]
Why?

**Comment by silas** [comment]
The motivation is so it works with coreupdate behind an nginx proxy.

The technical reason is because this project sets the `Opaque` property of the client request `URL` and hawk-go uses `URL.RequestURI()` to create the Hawk normalized request string. When `URL.Opaque` is not set this returns `Path+?+RawQuery` (which is [correct](https://github.com/hueniverse/hawk/commit/581e751f441958e6125cb807accbfefaee51017a) according to the hawk reference implementation), otherwise it returns [something else](https://golang.org/src/net/url/url.go#L853).

When nginx proxies requests to coreupdate it sets the absolute path in the request line instead of the absolute URL and invalidates the Hawk MAC.

**Comment by crawford** [comment]
Gotcha. Thanks.

**Comment by crawford** [comment]
LGTM

**Pull request merged**
